CREATE DATABASE HOSPITAL2;

USE HOSPITAL2;

CREATE TABLE PACIENTE(
	SUS INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(100)
);

CREATE TABLE MEDICO(
	CRM INT PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE CONSULTA(
	CMR INT,
    SUS INT,
    HORARIO DATETIME
);

DROP TABLE MEDICO;
DROP TABLE PACIENTE;
DROP TABLE CONSULTA;

-- O INSERT VAI COLOCAR DADOS NA TABELA
INSERT INTO MEDICO (CRM, NOME) VALUES ("26279", "DOUTOR BIQUINHO");
INSERT INTO PACIENTE (SUS, NOME) VALUES ("42882", "ANDRÉ SALPICAO");
INSERT INTO PACIENTE (SUS, NOME) VALUES ("45626", "ANDRÉ MAGRAO");
INSERT INTO PACIENTE (SUS, NOME) VALUES ("45625", "ANDRÉ SAO JOAO");

-- O SELECT EXIBE TUDO QUE TEM NA TABELA 
SELECT * FROM MEDICO;
SELECT * FROM PACIENTE;